INSERT INTO `AMENITY` (`gymId`, `freeParking`, `paidParking`, `allDay`, `showerFacilities`, `Sportswear`, `sharedLocker`, `personalLocker`, `unmanded`)
SELECT 
    gymIds.gymId,
    ROUND(RAND()) AS freeParking,
    ROUND(RAND()) AS paidParking,
    ROUND(RAND()) AS allDay,
    ROUND(RAND()) AS showerFacilities,
    ROUND(RAND()) AS Sportswear,
    ROUND(RAND()) AS sharedLocker,
    ROUND(RAND()) AS personalLocker,
    ROUND(RAND()) AS unmanded
FROM
    (SELECT 1 AS gymId UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
    UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
    UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15
    UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20
    UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL SELECT 25
    UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
    UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL SELECT 35
    UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL SELECT 40
    UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL SELECT 45
    UNION ALL SELECT 46 UNION ALL SELECT 47) AS gymIds;